import { GoogleGenerativeAI } from "@google/generative-ai";

const apiKey = process.env.GEMINI_API_KEY || "";
const genAI = apiKey ? new GoogleGenerativeAI(apiKey) : null;

export interface AgentLLMRequest {
  systemPrompt: string;
  userPrompt: string;
  responseSchema?: Record<string, unknown>;
  fallbackResponse: any;
}

export async function callAgentLLM<T = any>({
  systemPrompt,
  userPrompt,
  fallbackResponse,
}: AgentLLMRequest): Promise<{ data: T; isFallback: boolean; reasoning?: string }> {
  if (!genAI || !apiKey) {
    // Graceful smart fallback for offline / development mode
    return {
      data: fallbackResponse as T,
      isFallback: true,
      reasoning: "Generated by built-in Intelligent Inspection Engine (Set GEMINI_API_KEY to switch to live LLM).",
    };
  }

  try {
    const model = genAI.getGenerativeModel({
      model: "gemini-1.5-flash",
      systemInstruction: systemPrompt,
      generationConfig: {
        responseMimeType: "application/json",
      },
    });

    const result = await model.generateContent(userPrompt);
    const text = result.response.text();
    const parsed = JSON.parse(text);

    return {
      data: parsed as T,
      isFallback: false,
      reasoning: "Evaluated in real-time by Google Gemini 1.5 Flash Vision & Multi-Agent Model.",
    };
  } catch (error) {
    console.warn("Gemini API call failed, falling back to local heuristic:", error);
    return {
      data: fallbackResponse as T,
      isFallback: true,
      reasoning: "Fallback engine activated due to API timeout/limit.",
    };
  }
}
